name: Deploy

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - main
  release:
    types:
      - published

jobs:
  build_dist:
    name: Build Dist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build Dist
      run: pipx run build

    - name: Check Metadata
      run: pipx run twine check --strict dist/*

    - uses: actions/upload-artifact@v4
      with:
        path: dist/

  upload_all:
    name: Upload if release
    needs: [build_dist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    environment:
      name: pypi
      url: https://pypi.org/p/pyulog
    permissions:
      id-token: write

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - uses: actions/download-artifact@v4
      with:
        name: artifact
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4